# Docker compose file for starting postgres database and pgAdmin

version: "3.8"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: cijferhulp
            PGDATA: /var/lib/pgsql/data/pgdata
        volumes: 
            - ./pgdata:/var/lib/postgresql/data:z
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
            PGADMIN_DEFAULT_PASSWORD: postgres
        ports:
            - "80:80"

volumes: 
    pgdata:

    


