# Docker compose file for starting development postgres database and pgAdmin

version: "3.8"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_DB: ${PGDATABASE}
        volumes: 
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "80:80"

volumes: 
    pgdata:

    


