# Docker compose file for starting development postgres database and pgAdmin

version: "3.8"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_DB: ${PGDATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "${PGPORT}:${PGPORT}"

volumes:
    pgdata:




